spring.application.name=studycollabration
spring.datasource.url=jdbc:mysql://localhost:3306/study_collabration
spring.datasource.username=root
spring.datasource.password=Teja@1234
spring.jpa.show.sql=true
spring.jpa.hibernate.ddl-auto=update
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB